name: therapist-track

services:
  database: 
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: therapisttrack
    volumes:
      - ./Database/scripts:/docker-entrypoint-initdb.d/
      - mongo_data:/data/db
        

volumes:
  mongo_data:
    driver: local